language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t osmangurten/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true osmangurten/react-test npm test

after_success:
    - docker build -t osmangurten/multi-client ./client
    - docker build -t osmangurten/multi-nginx ./nginx
    - docker build -t osmangurten/multi-server ./server
    - docker build -t osmangurten/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push osmangurten/multi-client
    - docker push osmangurten/multi-nginx
    - docker push osmangurten/multi-server
    - docker push osmangurten/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-131194193142
    bucket_path: docker-multi2
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
